nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.7.0.cjs

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  # Add any package extensions if needed for compatibility

npmRegistryServer: 'https://registry.npmjs.org/'

logFilters:
  - code: YN0002 # Ignore "Removes a package from the dependencies but doesn't remove from node_modules" warning
    level: discard
  - code: YN0060 # Ignore "Peer dependency not provided" warning for optional peer dependencies
    level: discard
  - code: YN0013 # Ignore "fetch failed because of key exchange algorithm" warning
    level: discard
